//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affiliations_Proposed
    {
        public Nullable<int> AffiliationID { get; set; }
        public string AffiliationName { get; set; }
        public Nullable<int> PhysicianID { get; set; }
        public Nullable<int> EntityID { get; set; }
        public Nullable<int> AreaRecID { get; set; }
        public Nullable<int> SpecialityID { get; set; }
        public Nullable<int> LineID { get; set; }
        public string PhysicianClass { get; set; }
        public string BestTimeFrom { get; set; }
        public string BestTimeTo { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> Is_Approved { get; set; }
        public string EntityAddress { get; set; }
        public Nullable<int> EntityTypeID { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Fax { get; set; }
        public string EntityEmailAddress { get; set; }
        public string EntityWebSite { get; set; }
        public string PhysicianName { get; set; }
        public string EntityName { get; set; }
        public Nullable<bool> Is_Implemented { get; set; }
        public string RepName { get; set; }
        public Nullable<int> DMID { get; set; }
        public Nullable<int> BrickID { get; set; }
        public string NoOfPatients { get; set; }
        public string WatingTime { get; set; }
        public string PrescriptionHappit { get; set; }
        public string AdminComments { get; set; }
        public string DMComments { get; set; }
        public string RequestType { get; set; }
        public string Description { get; set; }
        public string EntityNameOld { get; set; }
        public string PhysicianNameOld { get; set; }
        public string EntityAddressOld { get; set; }
        public Nullable<int> AreaRecIDOld { get; set; }
        public Nullable<int> SpecialityIDOld { get; set; }
        public Nullable<int> EntityTypeIDOld { get; set; }
        public string NoOfPatientsOld { get; set; }
        public string WatingTimeOld { get; set; }
        public string PrescriptionHappitOld { get; set; }
        public Nullable<int> RealAffID { get; set; }
        public Nullable<int> SMID { get; set; }
        public Nullable<bool> SM_Approved { get; set; }
        public Nullable<int> SDID { get; set; }
        public Nullable<bool> SD_Approved { get; set; }
        public Nullable<int> COVP_ID { get; set; }
        public Nullable<bool> COVP_Approved { get; set; }
        public string SM_Comment { get; set; }
        public string SD_Comment { get; set; }
        public string CO_Comment { get; set; }
        public string Status { get; set; }
        public int RecID { get; set; }
        public string DMSignature { get; set; }
        public string SMSignature { get; set; }
        public string SDSignature { get; set; }
        public string COSignature { get; set; }
        public string AdminSignature { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> DMDate { get; set; }
        public Nullable<System.DateTime> SMDate { get; set; }
        public Nullable<System.DateTime> SDDate { get; set; }
        public Nullable<System.DateTime> CODate { get; set; }
        public Nullable<System.DateTime> AdminDate { get; set; }
        public string ProceedBySignature { get; set; }
        public Nullable<System.DateTime> ProceedByDate { get; set; }
        public Nullable<bool> ProceedBy { get; set; }
        public string NoOfOperations { get; set; }
        public string NoOfOperationsOld { get; set; }
    }
}
