//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandPriorityBySpecLine
    {
        public int RecID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> SpecialtyID { get; set; }
        public Nullable<int> BrandPriority { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
