//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesHistory
    {
        public int EmployeeID { get; set; }
        public Nullable<int> EmployeeHRCode { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> RepAreaID { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<int> ReportsTo { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> IsPilot { get; set; }
    }
}
