//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesMasterData
    {
        public int EmployeeHRCode { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeeUserName { get; set; }
        public string EmployeePassword { get; set; }
        public Nullable<bool> MustChangePassword { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
        public Nullable<System.DateTime> NextChangeDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsPilot { get; set; }
        public Nullable<int> NoOfVisitsPerDay { get; set; }
    }
}
