//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class NationalVaccation
    {
        public int VaccationID { get; set; }
        public Nullable<System.DateTime> VaccationDate { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> MonthID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> CycleID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Vaccation_Name { get; set; }
    }
}
