//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class PH_Pharmacies_Proposed
    {
        public Nullable<int> PharmacyID { get; set; }
        public string PharmacyName { get; set; }
        public Nullable<int> BrickID { get; set; }
        public string CusNameFromInMarket { get; set; }
        public string IsWrong { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public int RecID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> SD_Approved { get; set; }
        public string SD_Comment { get; set; }
        public Nullable<System.DateTime> SDDate { get; set; }
        public string RequestType { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> AreaRecID { get; set; }
        public Nullable<int> AreaRecIDOld { get; set; }
        public string PharmacyAddress { get; set; }
        public string PharmacyAddressOld { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Status { get; set; }
        public Nullable<int> SDID { get; set; }
        public string SDSign { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> EmpHRCode { get; set; }
    }
}
