//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmacyEmployee
    {
        public int PharmacyEmployeeRecID { get; set; }
        public Nullable<int> PharmacyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
