//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianValueByLine
    {
        public int RecID { get; set; }
        public Nullable<int> AffiliationID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<double> NoOfPatients { get; set; }
        public Nullable<double> WaitingTime { get; set; }
        public Nullable<double> SpecialtyValue { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public string PhysicianClass { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<double> PrescriptionHappit { get; set; }
        public Nullable<double> NoOfPatientsOld { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<int> LastModifierID { get; set; }
        public Nullable<double> NoOfPatientsOld2 { get; set; }
        public Nullable<double> PrescriptionHappitOld2 { get; set; }
        public Nullable<double> NoOfOperations { get; set; }
    }
}
