//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physician
    {
        public int PhysicianID { get; set; }
        public string PhysicianName { get; set; }
        public string MobileNumber { get; set; }
        public string TelNumber { get; set; }
        public string PhysicianEmailAddress { get; set; }
        public Nullable<int> SpecialtyID { get; set; }
        public Nullable<int> PhysicianOldCode { get; set; }
        public Nullable<int> EntryEmployeeID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    }
}
