//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Affiliations_only
    {
        public int AffiliationID { get; set; }
        public string AffiliationName { get; set; }
        public string AmounBrickName { get; set; }
        public string SpecialityCode { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<double> NoOfPatients { get; set; }
        public Nullable<double> PrescriptionHappit { get; set; }
        public string PhysicianClass { get; set; }
        public Nullable<double> WaitingTime { get; set; }
        public Nullable<int> PhysicianID { get; set; }
        public Nullable<int> EntityID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string BestTimeFrom { get; set; }
        public string BestTimeTo { get; set; }
        public string Notes { get; set; }
        public int SpecialityID { get; set; }
    }
}
