//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Entities
    {
        public int EntityID { get; set; }
        public string EntityName { get; set; }
        public Nullable<int> EntityCode { get; set; }
        public string EntityAddress { get; set; }
        public Nullable<int> EntityTypeID { get; set; }
        public Nullable<int> BrickID { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Fax { get; set; }
        public string EntityEmailAddress { get; set; }
        public string EntityWebSite { get; set; }
        public Nullable<int> EntryEmployeeID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string AmounBrickName { get; set; }
    }
}
