//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmounCRM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Affiliations_Admin
    {
        public int AffiliationID { get; set; }
        public string AffiliationName { get; set; }
        public string PhysicianName { get; set; }
        public string Entity_Name { get; set; }
        public Nullable<int> SpecialtyID { get; set; }
        public string SpecialityName { get; set; }
        public string PhysicianClass { get; set; }
        public string LineName { get; set; }
        public Nullable<int> PhysicianID { get; set; }
        public Nullable<int> EntityID { get; set; }
        public string AmounTerritoryName { get; set; }
        public Nullable<int> AreaRecID { get; set; }
        public string SupervisionArea { get; set; }
        public Nullable<int> AmounRegionID { get; set; }
        public string AmounRegionName { get; set; }
        public Nullable<int> AmounTerritoryID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> EmployeeHRCode { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeType { get; set; }
        public string SupervisorName { get; set; }
        public string EntityAddress { get; set; }
        public string SpecialityCode { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> SupervisionAreaID { get; set; }
        public Nullable<int> BrickID { get; set; }
        public string AmounBrickName { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string BestTimeFrom { get; set; }
        public string BestTimeTo { get; set; }
        public Nullable<double> NoOfPatients { get; set; }
        public Nullable<double> WaitingTime { get; set; }
        public Nullable<double> SpecialtyValue { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public string IsTargeted { get; set; }
        public Nullable<double> PrescriptionHappit { get; set; }
        public Nullable<double> NoOfPatientsOld { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Fax { get; set; }
        public string EntityEmailAddress { get; set; }
        public string EntityWebSite { get; set; }
        public Nullable<int> EntityTypeID { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<int> LastModifierID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public string IsTargeted2 { get; set; }
        public string AffiliationName2 { get; set; }
        public Nullable<int> RepAreaID { get; set; }
        public string Is_Targeted { get; set; }
        public string IsTargeted3 { get; set; }
        public Nullable<int> DirectorID { get; set; }
        public Nullable<int> DirectorHRCode { get; set; }
        public string DirectorName { get; set; }
        public Nullable<int> ComDirID { get; set; }
        public Nullable<int> ComDirHRCode { get; set; }
        public string ComDirName { get; set; }
        public Nullable<int> NoOfVisitsPerDay { get; set; }
        public Nullable<double> NoOfOperations { get; set; }
    }
}
